import type { ToolboxGroup, ToolboxTool } from "./types";

export const toolboxGroups: ToolboxGroup[] = [
  {
    id: "developer",
    label: "开发者常用",
    labelEn: "Developer",
    description: "处理结构化数据、编码和开发时常用值。",
  },
  {
    id: "text",
    label: "文本处理",
    labelEn: "Text",
    description: "快速清理、统计和预览文本。",
  },
  {
    id: "design",
    label: "前端设计",
    labelEn: "Design",
    description: "生成可直接使用的颜色和 CSS 参数。",
  },
  {
    id: "ai",
    label: "AI 提效",
    labelEn: "AI",
    description: "在本地整理提示词和估算上下文。",
  },
];

export const toolboxTools: ToolboxTool[] = [
  {
    slug: "json",
    group: "developer",
    title: "JSON 格式化",
    titleEn: "JSON Formatter",
    description: "格式化、压缩并校验 JSON。",
    placeholder: "粘贴 JSON",
    sample: '{"name":"abinzhao","focus":["Frontend","HarmonyOS","AI"]}',
  },
  {
    slug: "base64",
    group: "developer",
    title: "Base64 编解码",
    titleEn: "Base64 Codec",
    description: "使用 UTF-8 在本地编码或解码。",
    placeholder: "输入文本或 Base64",
    sample: "阿斌 / abinzhao",
  },
  {
    slug: "url-codec",
    group: "developer",
    title: "URL 编解码",
    titleEn: "URL Codec",
    description: "编码或解码 URL 组件。",
    placeholder: "输入 URL 或文本",
    sample: "https://example.com/?q=鸿蒙 AI",
  },
  {
    slug: "timestamp",
    group: "developer",
    title: "时间戳转换",
    titleEn: "Timestamp Converter",
    description: "Unix 秒、毫秒与 ISO 时间互转。",
    placeholder: "输入时间戳或日期",
    sample: "0",
  },
  {
    slug: "uuid",
    group: "developer",
    title: "UUID 生成",
    titleEn: "UUID Generator",
    description: "使用浏览器加密随机源生成 UUID v4。",
    placeholder: "无需输入",
    sample: "",
  },
  {
    slug: "text-stats",
    group: "text",
    title: "字数统计",
    titleEn: "Text Statistics",
    description: "统计字符、单词、行和非空行。",
    placeholder: "输入需要统计的文本",
    sample: "在鸿蒙上，用前端的方式，把 AI 变成应用。",
  },
  {
    slug: "unique-lines",
    group: "text",
    title: "文本去重",
    titleEn: "Unique Lines",
    description: "保留顺序并去除重复行。",
    placeholder: "每行一项",
    sample: "Frontend\nHarmonyOS\nAI\nFrontend",
  },
  {
    slug: "case-converter",
    group: "text",
    title: "命名转换",
    titleEn: "Case Converter",
    description: "转换 camel、Pascal、kebab 和 snake 命名。",
    placeholder: "输入词组或标识符",
    sample: "singularity engine",
  },
  {
    slug: "markdown-preview",
    group: "text",
    title: "Markdown 预览",
    titleEn: "Markdown Preview",
    description: "安全预览常用 Markdown 结构。",
    placeholder: "输入 Markdown",
    sample: "# abinzhao\n\n在鸿蒙上，用前端的方式，把 AI 变成应用。",
  },
  {
    slug: "color",
    group: "design",
    title: "颜色转换",
    titleEn: "Color Converter",
    description: "将 HEX 转换为 RGB、HSL 与 OKLCH。",
    placeholder: "输入 HEX，例如 #54e7ff",
    sample: "#54e7ff",
  },
  {
    slug: "gradient",
    group: "design",
    title: "渐变生成",
    titleEn: "Gradient Generator",
    description: "生成可复制的线性渐变。",
    placeholder: "每行一个 HEX 颜色",
    sample: "#54e7ff\n#4982ff\n#a18cff",
  },
  {
    slug: "shadow",
    group: "design",
    title: "阴影生成",
    titleEn: "Shadow Generator",
    description: "根据强度生成柔和 CSS 阴影。",
    placeholder: "输入 1–3",
    sample: "2",
  },
  {
    slug: "css-unit",
    group: "design",
    title: "CSS 单位换算",
    titleEn: "CSS Unit Converter",
    description: "按 16px 根字号换算 px 与 rem。",
    placeholder: "输入 24px 或 1.5rem",
    sample: "24px",
  },
  {
    slug: "prompt-builder",
    group: "ai",
    title: "Prompt 结构器",
    titleEn: "Prompt Builder",
    description: "按角色、目标、约束和输出格式组织提示词。",
    placeholder: "每行填写角色、目标、约束、输出格式",
    sample: "前端工程师\n审查组件\n只报告真实问题\nMarkdown",
  },
  {
    slug: "token-estimator",
    group: "ai",
    title: "Token 粗估",
    titleEn: "Token Estimator",
    description: "在本地粗略估算中英文 Token 数量。",
    placeholder: "输入需要估算的文本",
    sample: "让模型能力进入真实应用。",
  },
  {
    slug: "prompt-template",
    group: "ai",
    title: "提示词模板",
    titleEn: "Prompt Template",
    description: "把任务描述转成可复用结构。",
    placeholder: "输入任务描述",
    sample: "分析一个 Astro 站点的性能瓶颈",
  },
];

export function getTool(slug: string): ToolboxTool | undefined {
  return toolboxTools.find((tool) => tool.slug === slug);
}
